#include <string.h>

#include "protocol/enum.h"

/**
 * @brief Array of BACnet unit atoms.
 *
 * A collection of BACnet unit definitions, where each entry associates a unit
 * name with a corresponding integer identifier.
 *
 * Each entry follows the format:
 * - Name: The name of the unit (e.g., "meters_per_second_per_second").
 * - Identifier: An integer value representing the unit.
 *
 * @note For more information on BACnet units and their definitions, refer to:
 *       https://github.com/bacnet-stack/bacnet-stack/blob/master/src/bacnet/bacenum.h
 */
const enum_tuple_t BACNET_UNIT_ATOMS[] = {
  {"meters_per_second_per_second",           166},
  {"square_meters",                          0},
  {"square_centimeters",                     116},
  {"square_feet",                            1},
  {"square_inches",                          115},
  {"currency1",                              105},
  {"currency2",                              106},
  {"currency3",                              107},
  {"currency4",                              108},
  {"currency5",                              109},
  {"currency6",                              110},
  {"currency7",                              111},
  {"currency8",                              112},
  {"currency9",                              113},
  {"currency10",                             114},
  {"btu_per_hour_per_watt",                  47898},
  {"btu_per_watt_hour_seasonal",             47899},
  {"coefficient_of_performance",             47900},
  {"coefficient_of_performance_seasonal",    47901},
  {"kilowatt_per_ton_refrigeration",         47902},
  {"lumens_per_watt",                        47903},
  {"milliamperes",                           2},
  {"amperes",                                3},
  {"amperes_per_meter",                      167},
  {"amperes_per_square_meter",               168},
  {"ampere_square_meters",                   169},
  {"decibels",                               199},
  {"decibels_millivolt",                     200},
  {"decibels_volt",                          201},
  {"farads",                                 170},
  {"henrys",                                 171},
  {"ohms",                                   4},
  {"ohm_meters",                             172},
  {"milliohms",                              145},
  {"kilohms",                                122},
  {"megohms",                                123},
  {"microsiemens",                           190},
  {"millisiemens",                           202},
  {"siemens",                                173},
  {"siemens_per_meter",                      174},
  {"microsiemens_per_centimeter",            47909},
  {"millisiemens_per_centimeter",            47910},
  {"millisiemens_per_meter",                 47911},
  {"teslas",                                 175},
  {"volts",                                  5},
  {"millivolts",                             124},
  {"kilovolts",                              6},
  {"megavolts",                              7},
  {"volt_amperes",                           8},
  {"kilovolt_amperes",                       9},
  {"megavolt_amperes",                       10},
  {"volt_amperes_reactive",                  11},
  {"kilovolt_amperes_reactive",              12},
  {"megavolt_amperes_reactive",              13},
  {"volts_per_degree_kelvin",                176},
  {"volts_per_meter",                        177},
  {"degrees_phase",                          14},
  {"power_factor",                           15},
  {"webers",                                 178},
  {"joules",                                 16},
  {"kilojoules",                             17},
  {"kilojoules_per_kilogram",                125},
  {"megajoules",                             126},
  {"gigajoules",                             47925},
  {"terajoules",                             47926},
  {"watt_hours",                             18},
  {"kilowatt_hours",                         19},
  {"megawatt_hours",                         146},
  {"gigawatt_hours",                         47927},
  {"watt_reactive_hours",                    203},
  {"kilowatt_reactive_hours",                204},
  {"megawatt_reactive_hours",                205},
  {"gigawatt_reactive_hours",                47928},
  {"btus",                                   20},
  {"kilo_btus",                              147},
  {"mega_btus",                              148},
  {"therms",                                 21},
  {"ton_hours",                              22},
  {"active_energy_pulse_value",              47918},
  {"reactive_energy_pulse_value",            47919},
  {"apparent_energy_pulse_value",            47920},
  {"volt_squared_hour_pulse_value",          47921},
  {"ampere_squared_hour_pulse_value",        47922},
  {"joules_per_kilogram_dry_air",            23},
  {"kilojoules_per_kilogram_dry_air",        149},
  {"megajoules_per_kilogram_dry_air",        150},
  {"btus_per_pound_dry_air",                 24},
  {"btus_per_pound",                         117},
  {"joules_per_degree_kelvin",               127},
  {"kilojoules_per_degree_kelvin",           151},
  {"megajoules_per_degree_kelvin",           152},
  {"joules_per_kilogram_degree_kelvin",      128},
  {"newton",                                 153},
  {"cycles_per_hour",                        25},
  {"cycles_per_minute",                      26},
  {"hertz",                                  27},
  {"kilohertz",                              129},
  {"megahertz",                              130},
  {"per_day",                                47823},
  {"per_hour",                               131},
  {"per_millisecond",                        47824},
  {"grams_of_water_per_kilogram_dry_air",    28},
  {"percent_relative_humidity",              29},
  {"micrometers",                            194},
  {"millimeters",                            30},
  {"centimeters",                            118},
  {"kilometers",                             193},
  {"meters",                                 31},
  {"inches",                                 32},
  {"feet",                                   33},
  {"yards",                                  47825},
  {"miles",                                  47826},
  {"nautical_miles",                         47827},
  {"candelas",                               179},
  {"candelas_per_square_meter",              180},
  {"watts_per_square_foot",                  34},
  {"watts_per_square_meter",                 35},
  {"lumens",                                 36},
  {"luxes",                                  37},
  {"foot_candles",                           38},
  {"nanograms",                              47828},
  {"micrograms",                             47829},
  {"milligrams",                             196},
  {"grams",                                  195},
  {"kilograms",                              39},
  {"pounds_mass",                            40},
  {"tons",                                   41},
  {"metric_tonnes",                          47830},
  {"short_tons",                             47831},
  {"long_tons",                              47832},
  {"grams_per_second",                       154},
  {"grams_per_minute",                       155},
  {"grams_per_hour",                         47833},
  {"grams_per_day",                          47834},
  {"kilograms_per_second",                   42},
  {"kilograms_per_minute",                   43},
  {"kilograms_per_hour",                     44},
  {"kilograms_per_day",                      47835},
  {"pounds_mass_per_second",                 119},
  {"pounds_mass_per_minute",                 45},
  {"pounds_mass_per_hour",                   46},
  {"tons_per_hour",                          156},
  {"short_tons_per_second",                  47836},
  {"short_tons_per_minute",                  47837},
  {"short_tons_per_hour",                    47838},
  {"short_tons_per_day",                     47839},
  {"metric_tonnes_per_second",               47840},
  {"metric_tonnes_per_minute",               47841},
  {"metric_tonnes_per_hour",                 47842},
  {"metric_tonnes_per_day",                  47843},
  {"long_tons_per_second",                   47844},
  {"long_tons_per_minute",                   47845},
  {"long_tons_per_hour",                     47846},
  {"long_tons_per_day",                      47847},
  {"milliwatts",                             132},
  {"watts",                                  47},
  {"kilowatts",                              48},
  {"megawatts",                              49},
  {"gigawatts",                              47924},
  {"btus_per_second",                        47848},
  {"btus_per_minute",                        47849},
  {"btus_per_hour",                          50},
  {"btus_per_day",                           47850},
  {"kilo_btus_per_second",                   47851},
  {"kilo_btus_per_minute",                   47852},
  {"kilo_btus_per_hour",                     157},
  {"kilo_btus_per_day",                      47853},
  {"mega_btus_per_second",                   47854},
  {"mega_btus_per_minute",                   47855},
  {"mega_btus_per_hour",                     47856},
  {"mega_btus_per_day",                      47857},
  {"joules_per_second",                      47858},
  {"joules_per_minute",                      47859},
  {"joules_per_day",                         47860},
  {"kilojoules_per_second",                  47861},
  {"kilojoules_per_minute",                  47862},
  {"kilojoules_per_hour",                    47863},
  {"kilojoules_per_day",                     47864},
  {"megajoules_per_second",                  47865},
  {"megajoules_per_minute",                  47866},
  {"megajoules_per_hour",                    47867},
  {"megajoules_per_day",                     47868},
  {"horsepower",                             51},
  {"tons_refrigeration",                     52},
  {"pascals",                                53},
  {"hectopascals",                           133},
  {"kilopascals",                            54},
  {"millibars",                              134},
  {"bars",                                   55},
  {"pounds_force_per_square_inch",           56},
  {"pounds_force_per_square_inch_absolute",  47907},
  {"pounds_force_per_square_inch_gauge",     47908},
  {"millimeters_of_water",                   206},
  {"centimeters_of_water",                   57},
  {"inches_of_water",                        58},
  {"millimeters_of_mercury",                 59},
  {"centimeters_of_mercury",                 60},
  {"inches_of_mercury",                      61},
  {"degrees_celsius",                        62},
  {"degrees_celsius_per_day",                47869},
  {"kelvin",                                 63},
  {"kelvin_per_day",                         47870},
  {"kelvin_per_hour",                        181},
  {"kelvin_per_minute",                      182},
  {"degrees_fahrenheit",                     64},
  {"degrees_fahrenheit_per_day",             47871},
  {"degree_days_celsius",                    65},
  {"degree_days_fahrenheit",                 66},
  {"delta_degrees_celsius",                  47872},
  {"delta_degrees_fahrenheit",               120},
  {"delta_kelvin",                           121},
  {"years",                                  67},
  {"months",                                 68},
  {"weeks",                                  69},
  {"days",                                   70},
  {"hours",                                  71},
  {"minutes",                                72},
  {"seconds",                                73},
  {"hundredths_seconds",                     158},
  {"milliseconds",                           159},
  {"newton_meters",                          160},
  {"pound_force_feet",                       47904},
  {"pound_force_inches",                     47905},
  {"ounce_force_inches",                     47906},
  {"millimeters_per_second",                 161},
  {"millimeters_per_minute",                 162},
  {"meters_per_second",                      74},
  {"meters_per_minute",                      163},
  {"meters_per_hour",                        164},
  {"kilometers_per_hour",                    75},
  {"feet_per_second",                        76},
  {"feet_per_minute",                        77},
  {"miles_per_hour",                         78},
  {"cubic_feet",                             79},
  {"cubic_meters",                           80},
  {"imperial_gallons",                       81},
  {"milliliters",                            197},
  {"liters",                                 82},
  {"us_gallons",                             83},
  {"millions_of_us_gallons",                 47912},
  {"millions_of_imperial_gallons",           47913},
  {"volume1",                                47937},
  {"volume2",                                47938},
  {"volume3",                                47939},
  {"volume4",                                47940},
  {"volume5",                                47941},
  {"volume6",                                47942},
  {"volume7",                                47943},
  {"volume8",                                47944},
  {"volume9",                                47945},
  {"volume10",                               47946},
  {"cubic_feet_per_second",                  142},
  {"cubic_feet_per_minute",                  84},
  {"cubic_feet_per_hour",                    191},
  {"million_cubic_feet_per_minute",          47873},
  {"million_cubic_feet_per_day",             47874},
  {"cubic_meters_per_second",                85},
  {"cubic_meters_per_minute",                165},
  {"cubic_meters_per_hour",                  135},
  {"imperial_gallons_per_second",            47875},
  {"imperial_gallons_per_minute",            86},
  {"imperial_gallons_per_hour",              47876},
  {"imperial_gallons_per_day",               47877},
  {"milliliters_per_second",                 198},
  {"milliliters_per_minute",                 47914},
  {"liters_per_second",                      87},
  {"liters_per_minute",                      88},
  {"liters_per_hour",                        136},
  {"liters_per_day",                         47878},
  {"us_gallons_per_second",                  47879},
  {"us_gallons_per_minute",                  89},
  {"us_gallons_per_hour",                    192},
  {"us_gallons_per_day",                     47880},
  {"cubic_meter_pulse_value",                47923},
  {"volumetric_flow1",                       47947},
  {"volumetric_flow2",                       47948},
  {"volumetric_flow3",                       47949},
  {"volumetric_flow4",                       47950},
  {"volumetric_flow5",                       47951},
  {"volumetric_flow6",                       47952},
  {"volumetric_flow7",                       47953},
  {"volumetric_flow8",                       47954},
  {"volumetric_flow9",                       47955},
  {"volumetric_flow10",                      47956},
  {"degrees_angular",                        90},
  {"degrees_celsius_per_hour",               91},
  {"degrees_celsius_per_minute",             92},
  {"degrees_fahrenheit_per_hour",            93},
  {"degrees_fahrenheit_per_minute",          94},
  {"joule_seconds",                          183},
  {"kilograms_per_cubic_meter",              186},
  {"kw_hours_per_square_meter",              137},
  {"kw_hours_per_square_foot",               138},
  {"megajoules_per_square_meter",            139},
  {"megajoules_per_square_foot",             140},
  {"no_units",                               95},
  {"newton_seconds",                         187},
  {"newtons_per_meter",                      188},
  {"parts_per_million",                      96},
  {"parts_per_billion",                      97},
  {"percent",                                98},
  {"percent_obscuration_per_foot",           143},
  {"percent_obscuration_per_meter",          144},
  {"percent_per_second",                     99},
  {"percent_per_minute",                     47881},
  {"percent_per_hour",                       47882},
  {"percent_per_day",                        47883},
  {"per_minute",                             100},
  {"per_second",                             101},
  {"psi_per_degree_fahrenheit",              102},
  {"radians",                                103},
  {"radians_per_second",                     184},
  {"revolutions_per_minute",                 104},
  {"square_meters_per_newton",               185},
  {"watts_per_meter_per_degree_kelvin",      189},
  {"watts_per_square_meter_degree_kelvin",   141},
  {"per_mille",                              207},
  {"per_million",                            47884},
  {"per_billion",                            47885},
  {"grams_per_gram",                         208},
  {"micrograms_per_gram",                    47886},
  {"nanograms_per_gram",                     47887},
  {"kilograms_per_kilogram",                 209},
  {"grams_per_kilogram",                     210},
  {"milligrams_per_gram",                    211},
  {"milligrams_per_kilogram",                212},
  {"micrograms_per_kilogram",                47888},
  {"nanograms_per_kilogram",                 47889},
  {"grams_per_milliliter",                   213},
  {"milligrams_per_milliliter",              47890},
  {"micrograms_per_milliliter",              47891},
  {"nanograms_per_milliliter",               47892},
  {"kilograms_per_liter",                    47893},
  {"grams_per_liter",                        214},
  {"milligrams_per_liter",                   215},
  {"micrograms_per_liter",                   216},
  {"nanograms_per_liter",                    47894},
  {"grams_per_cubic_meter",                  217},
  {"milligrams_per_cubic_meter",             218},
  {"micrograms_per_cubic_meter",             219},
  {"nanograms_per_cubic_meter",              220},
  {"grams_per_cubic_centimeter",             221},
  {"milligrams_per_cubic_centimeter",        47895},
  {"micrograms_per_cubic_centimeter",        47896},
  {"nanograms_per_cubic_centimeter",         47897},
  {"becquerels",                             222},
  {"kilobecquerels",                         223},
  {"megabecquerels",                         224},
  {"gray",                                   225},
  {"milligray",                              226},
  {"microgray",                              227},
  {"sieverts",                               228},
  {"millisieverts",                          229},
  {"microsieverts",                          230},
  {"microsieverts_per_hour",                 231},
  {"decibels_a",                             232},
  {"nephelometric_turbidity_unit",           233},
  {"ph",                                     234},
  {"grams_per_square_meter",                 235},
  {"minutes_per_degree_kelvin",              236},
  {"degrees_lovibond",                       47816},
  {"alcohol_by_volume",                      47817},
  {"international_bittering_units",          47818},
  {"european_bitterness_units",              47819},
  {"degrees_plato",                          47820},
  {"specific_gravity",                       47821},
  {"european_brewing_convention",            47822},
  {"mils_per_year",                          47915},
  {"millimeters_per_year",                   47916},
  {"pulses_per_minute",                      47917},
  {"bits_per_second",                        47929},
  {"kilobits_per_second",                    47930},
  {"megabits_per_second",                    47931},
  {"gigabits_per_second",                    47932},
  {"bytes_per_second",                       47933},
  {"kilobytes_per_second",                   47934},
  {"megabytes_per_second",                   47935},
  {"gigabytes_per_second",                   47936},
  {"site_unit1",                             47958},
  {"site_unit2",                             47959},
  {"site_unit3",                             47960},
  {"site_unit4",                             47961},
  {"site_unit5",                             47962},
  {"site_unit6",                             47963},
  {"site_unit7",                             47964},
  {"site_unit8",                             47965},
  {"site_unit9",                             47966},
  {"site_unit10",                            47967},
  {"ohm_meter_squared_per_meter",            237},
  {"ampere_seconds",                         238},
  {"volt_ampere_hours",                      239},
  {"kilovolt_ampere_hours",                  240},
  {"megavolt_ampere_hours",                  241},
  {"volt_ampere_reactive_hours",             242},
  {"kilovolt_ampere_reactive_hours",         243},
  {"megavolt_ampere_reactive_hours",         244},
  {"volt_square_hours",                      245},
  {"ampere_square_hours",                    246},
  {"joule_per_hours",                        247},
  {"cubic_feet_per_day",                     248},
  {"cubic_meters_per_day",                   249},
  {"watt_hours_per_cubic_meter",             250},
  {"joules_per_cubic_meter",                 251},
  {"mole_percent",                           252},
  {"pascal_seconds",                         253},
  {"million_standard_cubic_feet_per_minute", 254},
  {"reserved_range_max",                     255},
  {"proprietary_range_min",                  256},
  {"proprietary_range_max",                  47807},
  {"reserved_range_min2",                    47808},
  {"standard_cubic_feet_per_day",            47808},
  {"million_standard_cubic_feet_per_day",    47809},
  {"thousand_cubic_feet_per_day",            47810},
  {"thousand_standard_cubic_feet_per_day",   47811},
  {"pounds_mass_per_day",                    47812},
  {"millirems",                              47814},
  {"millirems_per_hour",                     47815},
  {NULL,                                     -1},
};

/**
 * @brief Retrieves the enum value corresponding to a specified string
 *        identifier.
 *
 * The purpose is to map string identifiers to their associated integer values
 * within a collection of predefined pairs. When provided with a string, the
 * goal is to locate its associated integer representation.
 *
 * @param enum_tuples A pointer to an array of structures that pair string
 *                    identifiers with integer values. The array should be
 *                    terminated by a sentinel structure where the `atom` member
 *                    is NULL, indicating the end of valid entries.
 *
 * @param atom A string identifier.
 *
 * @return The integer value associated with the provided string identifier.
 *         If the identifier is not found within the array, -1 is returned.
 *
 * @note The search process is case-sensitive, so the input string must match
 *       the identifiers exactly.
 *
 * @example
 * const enum_tuple_t my_enums[] = {
 *   {"ONE",   1},
 *   {"TWO",   2},
 *   {"THREE", 3},
 *   {NULL,    0},
 * };
 *
 * int result = find_enum_value(my_enums, "TWO"); // Returns 2
 * int not_found = find_enum_value(my_enums, "FOUR"); // Returns -1
 */
int find_enum_value(const enum_tuple_t* enum_tuples, const char* atom)
{
  for (size_t index = 0; enum_tuples[index].atom != NULL; index++) {
    if (strcmp(enum_tuples[index].atom, atom) == 0) {
      return enum_tuples[index].value;
    }
  }

  return -1;
}
